version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://mostafataha:12341234@cluster0.2l0nv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: